# Generated by Django 3.2.4 on 2021-07-09 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('day', models.CharField(choices=[('Mo', 'Monday'), ('Tu', 'Tuesday'), ('We', 'Wednesday'), ('Th', 'Thursday'), ('Fr', 'Friday'), ('Sa', 'Saturday'), ('Su', 'Sunday')], max_length=9)),
                ('tiime', models.CharField(choices=[('0.0', '0:00'), ('1.0', '1:00'), ('2.0', '2:00'), ('3.0', '3:00'), ('4.0', '4:00'), ('5.0', '5:00'), ('6.0', '6:00'), ('7.0', '7:00'), ('8.0', '8:00'), ('9.0', '9:00'), ('10.0', '10:00'), ('11.0', '11:00'), ('12.0', '12:00'), ('13.0', '13:00'), ('14.0', '14:00'), ('15.0', '15:00'), ('16.0', '16:00'), ('17.0', '17:00'), ('18.0', '18:00'), ('19.0', '19:00'), ('20.0', '20:00'), ('21.0', '21:00'), ('22.0', '22:00'), ('23.0', '23:00')], max_length=5)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scheduler.table')),
            ],
        ),
    ]
