# Generated by Django 3.2.4 on 2021-07-09 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='tiime',
            new_name='time',
        ),
    ]
