# Generated by Django 3.2.4 on 2021-07-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduler', '0005_auto_20210719_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='time',
            field=models.JSONField(),
        ),
    ]
